### ISSUE TITLE
Cannot find module 'react-dom'

### ISSUE THREAD

**Issue by mspkom** [praneybehl/meteor-react-hammerjs#1]
Having installed the package 'meteor add praneybehl:react-hammerjs' to my meteor-react-project, I get the following console-error:

Errors prevented startup:                  

   While processing files with cosmos:browserify (for target web.browser):
   packages/praneybehl:react-hammerjs/package.browserify.js: Cannot find module 'react-dom' from
   '/Users/mspkom/.meteor/packages/praneybehl_react-hammerjs/.0.4.2.13aqeis++os+web.browser+web.cordova/npm/node_modules/react-hammerjs/src'

=> Your application has errors. Waiting for file change.

**Comment by praneybehl** [comment]
I have updated the react-dom dependencies. Please remove the package and install praneybehl:react:hammerjs@0.4.2_1 see if it fixes that error.

cheers!

**Comment by praneybehl** [comment]
I've bumped the version and trying to push update to atmosphere but for some odd reason the new package updates are not being pushed. So odd.

**Comment by mspkom** [comment]
So how do you think we can handle this issue?

**Comment by praneybehl** [comment]
Not sure what was the issue, but to fix it the only way I found was to remove the package and then rename and re-publish, it sucks although, luckily there was one me using it so far so it should be ok.

So here it is:
remove the old package and use 

``` JS
meteor add praneybehl:reactjs-hammerjs
```

let me know if the issue persists.
thanks for your patience

**Comment by praneybehl** [comment]
@mspkom did you getting it working?

**Comment by mspkom** [comment]
yes. i think we can close this now.

thanks for your support.

**Comment by praneybehl** [comment]
cheers!
